name: Repository setup

on:
  push:
    branches: [main]

jobs:
  setup:

    if: ${{ github.event.created }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Replace repository name
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "\\{\\{GITHUB_REPOSITORY\\}\\}"
          replace: ${GITHUB_REPOSITORY}
      - name: Replace repository name without owner
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "\\{\\{GITHUB_REPOSITORY_WITHOUT_OWNER\\}\\}"
          replace: ${GITHUB_REPOSITORY#*\/}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated repository setup
          commit_options: "--no-verify --signoff"
